### ISSUE TITLE
Frontend slow with many concurrent users

### ISSUE THREAD

**Issue by rth** [paris-saclay-cds/ramp-board#509]
The server can be quite slow when accessed by multiple simultaneous users. For instance, here are load tests for a few pages with [drill](https://github.com/fcsonline/drill).

**benchmark.yml**
<details>

```yml
---

concurrency: 30
base: 'https://ramp.studio'
iterations: 32
rampup: 5

plan:
  - name: Fetch homepage
    request:
      url: /


  - name: Fetch event
    request:
      url: /events/{{ item }}
    with_items:
      - air_passengers_dssp_14
      - air_passengers_m2mosef2020
      - air_passengers_py4ds2020

  - name: Fetch problems
    request:
      url: /problems
```

</details>

where 

```bash
drill --benchmark benchmark.yml --stats
```

with 30 concurrent connections produces ,
```
Fetch homepage            Total requests            32
Fetch homepage            Median time per request   155ms

Fetch event               Total requests            96
Fetch event               Median time per request   109ms

Fetch problems            Total requests            32
Fetch problems            Median time per request   2033ms
```
so the issue seems to be particularly with the `/problems` page, I suspect because of of a DB query in a double loop [here](https://github.com/paris-saclay-cds/ramp-board/blob/7e975d01c080278b2101a5ca48461bc7e5dcd3ea/ramp-frontend/ramp_frontend/views/ramp.py#L105).

The solutions could be to either,
 - to refactor that code to not make so many DB queries if possible
 - cache the whole page either with nginx or something like [caddy](https://github.com/caddyserver/caddy) + [caddy-cache](https://github.com/nicolasazrak/caddy-cache)
